### ISSUE TITLE
In dark mode, Button keeps background color when disabled

### ISSUE THREAD

**Issue by drewbitt** [svelteuidev/svelteui#297] opened 2023-02-01 03:44 UTC
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

This can be seen on https://www.svelteui.org/core/button (it keeps blue). Although this could be a style choice, all the other inputs & action components, like the Checkbox, lose their color when disabled. 

### Steps To Reproduce

Svelteui 0.9, docs website

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by BeeMargarida** [comment] 2023-02-01 08:34
Definitely a bug, thank you for reporting it. It's probably a regression due to changes in the styleAPI

**Comment by BeeMargarida** [comment] 2023-02-16 21:46
Fixed in the new release 0.10.0

**Closed by BeeMargarida** 2023-02-16 21:46 UTC
Labels: bug
