### ISSUE TITLE
Changing the gradient colours doesn't reflect on the demo

### ISSUE THREAD

**Issue by Caladan08** [svelteuidev/svelteui#225] opened 2022-11-16 11:08 UTC
### Link to the page where something isn't quite right

https://www.svelteui.org/core/badge
https://www.svelteui.org/core/theme-icon
https://www.svelteui.org/core/text

### Exact quote of what is wrong

When we scroll down to the "Gradient Variant" section of the `Text`, `ThemeIcon` and `Badge` component, there is a demo to show how we can use the `gradient` property they have. At least, that is what it is supposed to do. When we change the colours in the palette to the right or when we change the degree count in the right, the changes aren't reflected in the demo component

---

For the `Badge` component (for all of them, it is the same):

Before changing the colours (the default options when I load the page):

<img width="1190" alt="Before Changing" src="https://user-images.githubusercontent.com/94300963/202164227-56df1cf2-6e97-4df3-90f8-6e9f844670b5.png">

After changing the values (the Badge demo stays the same):

<img width="1190" alt="After Changing" src="https://user-images.githubusercontent.com/94300963/202164444-4851db36-624e-4729-a3cd-85be9c4f1369.png">

### Are you willing to create pull request with the fix?

Yes

**Comment by Caladan08** [comment] 2022-11-16 11:10
I am willing to create a pull request but it might take some time since I am not quite sure on how to do it. Will have to check the docs of other components and see how to do it

**Comment by Caladan08** [comment] 2022-11-16 15:02
After going through the docs a little more, I noticed that the "Gradient Variant" section of the `Text` and `ThemeIcon` components also had the same problem.

**Comment by BeeMargarida** [comment] 2022-11-16 19:33
Thank you, I will investigate this! If you want to create a pull request with a fix, I can help you with it

**Comment by Caladan08** [comment] 2022-11-20 13:14
In other components which had the `gradient` property (such as the `<Button />` component), instead of a `ConfiguratorDemo` (I believe that's what it's called), there was just a simple `CodeDemo` with examples and how to code each of them which looks like this:

<img width="1189" alt="Button Gradient" src="https://user-images.githubusercontent.com/94300963/202903907-c5e2f467-57b8-4d3a-a073-73db19fd3e90.png">


So, to keep some consistency, I could replicate that in the `<Badge />`, `<ThemeIcon />` and `<Text />` components. Or should I try to fix the gradient palette instead?

**Comment by BeeMargarida** [comment] 2022-11-20 15:12
> In other components which had the `gradient` property (such as the `<Button />` component), instead of a `ConfiguratorDemo` (I believe that's what it's called), there was just a simple `CodeDemo` with examples and how to code each of them which looks like this:
> 
> <img alt="Button Gradient" width="1189" src="https://user-images.githubusercontent.com/94300963/202903907-c5e2f467-57b8-4d3a-a073-73db19fd3e90.png">
> 
> So, to keep some consistency, I could replicate that in the `<Badge />`, `<ThemeIcon />` and `<Text />` components. Or should I try to fix the gradient palette instead?

It seems like the problem is in the `<Configurator>` and `<ControlsRenderer>` components in the `demos` package and not in the components themselves. Basically this is a docs error

**Comment by Caladan08** [comment] 2022-11-20 15:32
Yeah. Every page which had this type of gradient palette didn't work properly. The problem was that editing the gradient palette didn't change the code given in the example which is why the demo didn't change. So, we could just remove it and stick to the way the `<Button />` component

**Comment by BeeMargarida** [comment] 2022-11-20 15:34
@Caladan08 I found the solution, this one was a bit tricky. The problem was related to the way the propagation was being made in the `CompositeControl`, it was sending the wrong data, both to the component and to the code generated from it. Thank you for your investigation, it helped to pin point the root cause of the problem. I'll open PR with the fix

**Comment by Caladan08** [comment] 2022-11-20 15:35
Thanks for the fix!

**Comment by BeeMargarida** [comment] 2022-11-20 16:10
Closing now since it's fixed, but still missing a release of the docs

**Closed by BeeMargarida** 2022-11-20 16:10 UTC
