### ISSUE TITLE
[Feature Request] Table

### ISSUE THREAD

**Issue by michalss** [svelteuidev/svelteui#499] opened 2024-06-30 16:03 UTC
### Usage example, including component, action, motion, or utility API

Hi there is not any table component ?

### Do you want to contribute this feature and create a pull request

Yes

**Comment by BeeMargarida** [comment] 2024-07-01 13:22
Hey, there's a first draft of it, but right now we stopped all new features development to focus on migrating the library to svelte 5, see [here](https://github.com/svelteuidev/svelteui/issues/491)

**Comment by BeeMargarida** [comment] 2024-07-01 13:22
Also duplicate of https://github.com/svelteuidev/svelteui/issues/406

**Closed by BeeMargarida** 2024-07-01 13:22 UTC
Labels: duplicate
